<svg
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="<?= $class ?? ''; ?> flex-none"
>
  <polygon
    class="st0"
    points="21.3,21.1 9.9,2.9 2.7,2.9 14.1,21.1 "
  />
  <line
    class="st0"
    x1="2.7"
    y1="21.1"
    x2="9.9"
    y2="14.5"
  />
  <line
    class="st0"
    x1="14.1"
    y1="9.5"
    x2="21.3"
    y2="2.9"
  />
</svg>
