    <footer class="
      wrapper py-6 flex items-center gap-2 text-center flex-col
      lg:py-8 lg:flex-row lg:justify-between
    ">
      <div class="px-4 py-1">
        &copy; <?= date('Y'); ?> - <?= get_bloginfo('name'); ?>
      </div>

      <?php if ($value = get_field('siret', 'option')) { ?>
        <div class="px-4 py-1">
          Siret: <?= $value; ?>
        </div>
      <?php } ?>
    </footer>

    <?php wp_footer(); ?>
  </body>
</html>
